version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: redis-sellsy
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: ["redis-server", "--appendonly", "yes"]

  webhook-listener:
    build: .
    container_name: sellsy-listener
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - redis
