# Dockerfile.worker
FROM node:20-alpine

WORKDIR /app/worker

# Copy package files
COPY package*.json ./
RUN npm install --only=production

# Copy source code
COPY worker.js ./

# Create non-root user
RUN addgroup -g 1001 -S nodejs
RUN adduser -S nodeuser -u 1001

# Change ownership
RUN chown -R nodeuser:nodejs /app
USER nodeuser

EXPOSE 3001

CMD ["node", "worker.js"]
